server:
  port: 8069

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: DB-service
          uri: lb://DB-service
          predicates:
            - Path=/item/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"